# Generated by Django 4.2.8 on 2023-12-15 13:13

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('website', models.URLField(blank=True, default='')),
                ('email', models.EmailField(max_length=256)),
                ('sector', models.CharField(choices=[('AE', 'Aerospace'), ('AG', 'Agriculture'), ('AU', 'Automotive'), ('BT', 'Biotechnology'), ('CO', 'Consulting'), ('EN', 'Entertainment'), ('FI', 'Finance'), ('HE', 'Healthcare'), ('HO', 'Hospitality'), ('LO', 'Logistics'), ('MA', 'Manufacturing'), ('ME', 'Media'), ('PH', 'Pharmaceutical'), ('RE', 'Real Estate'), ('SS', 'Social Services'), ('SP', 'Sports'), ('TE', 'Technology'), ('TC', 'Telecommunications'), ('TO', 'Tourism')], default='AG', max_length=128)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('location', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=256)),
                ('sector', models.CharField(choices=[('AE', 'Aerospace'), ('AG', 'Agriculture'), ('AU', 'Automotive'), ('BT', 'Biotechnology'), ('CO', 'Consulting'), ('EN', 'Entertainment'), ('FI', 'Finance'), ('HE', 'Healthcare'), ('HO', 'Hospitality'), ('LO', 'Logistics'), ('MA', 'Manufacturing'), ('ME', 'Media'), ('PH', 'Pharmaceutical'), ('RE', 'Real Estate'), ('SS', 'Social Services'), ('SP', 'Sports'), ('TE', 'Technology'), ('TC', 'Telecommunications'), ('TO', 'Tourism')], default='AG', max_length=128)),
            ],
        ),
    ]
